[project]
name = "konto-ingestion"
version = "0.1.0"
description = "Ingestion pipeline for Norwegian legal and regulatory texts data"
requires-python = ">=3.10"
dependencies = [
  "beautifulsoup4>=4.12",
  "lxml>=5.2",
  "requests>=2.32",
  "pydantic>=2.8",
  "python-dateutil>=2.9",
  "types-beautifulsoup4>=4.12.0.20250516",
  "types-requests>=2.32.4.20250913",
  "dynaconf>=3.2.11",
  "mypy>=1.18.2",
]

[project.scripts]
konto-ingest = "main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["modules", "scripts"]
include = ["main.py", "configs/*", "data/*", "settings.toml"]
