"""
Chart of Accounts seed data generator.
Generates Norwegian Standard (NS 4102) chart of accounts.
"""

import json
from datetime import datetime
from pathlib import Path

from ..logger import logger
from ..schemas import ChartOfAccountsEntry
from ..settings import get_silver_dir


def get_ns4102_accounts() -> list[ChartOfAccountsEntry]:
    """Norwegian Standard NS 4102 chart of accounts for SMEs."""
    timestamp = datetime.now().isoformat()

    accounts_data = [
        {
            "account_id": "1000",
            "account_label": "Forskning og utvikling",
            "account_class": "1",
            "account_class_label": "Eiendeler",
            "account_group": "10",
            "account_group_label": "Immaterielle eiendeler",
            "description": "Aktiverte kostnader til forskning og utvikling",
            "account_type": "asset",
            "normal_balance": "debit",
            "examples": ["FoU-prosjekter", "Produktutvikling"],
            "related_vat_codes": [],
        },
        {
            "account_id": "1100",
            "account_label": "Tomter",
            "account_class": "1",
            "account_class_label": "Eiendeler",
            "account_group": "11",
            "account_group_label": "Fast eiendom",
            "description": "Tomter og grunn",
            "account_type": "asset",
            "normal_balance": "debit",
            "examples": ["Næringstomter", "Byggegrunn"],
            "related_vat_codes": [],
        },
        {
            "account_id": "1200",
            "account_label": "Bygninger",
            "account_class": "1",
            "account_class_label": "Eiendeler",
            "account_group": "12",
            "account_group_label": "Maskiner og inventar",
            "description": "Bygninger og bygningsmessige anlegg",
            "account_type": "asset",
            "normal_balance": "debit",
            "examples": ["Kontorbygg", "Produksjonshaller"],
            "related_vat_codes": [],
        },
        {
            "account_id": "1220",
            "account_label": "Maskiner og anlegg",
            "account_class": "1",
            "account_class_label": "Eiendeler",
            "account_group": "12",
            "account_group_label": "Maskiner og inventar",
            "description": "Maskiner, utstyr og anlegg",
            "account_type": "asset",
            "normal_balance": "debit",
            "examples": ["Produksjonsutstyr", "Maskinpark"],
            "related_vat_codes": ["HIGH"],
        },
        {
            "account_id": "1240",
            "account_label": "Inventar",
            "account_class": "1",
            "account_class_label": "Eiendeler",
            "account_group": "12",
            "account_group_label": "Maskiner og inventar",
            "description": "Inventar, utstyr og verktøy",
            "account_type": "asset",
            "normal_balance": "debit",
            "examples": ["Kontormøbler", "IT-utstyr"],
            "related_vat_codes": ["HIGH"],
        },
        {
            "account_id": "1500",
            "account_label": "Bankinnskudd",
            "account_class": "1",
            "account_class_label": "Eiendeler",
            "account_group": "15",
            "account_group_label": "Bankinnskudd",
            "description": "Innskudd i bank",
            "account_type": "asset",
            "normal_balance": "debit",
            "examples": ["Brukskonto", "Sparekonto"],
            "related_vat_codes": [],
        },
        {
            "account_id": "1509",
            "account_label": "Tap på kundefordringer",
            "account_class": "1",
            "account_class_label": "Eiendeler",
            "account_group": "15",
            "account_group_label": "Kundefordringer",
            "description": "Avskrivning av tapte kundefordringer",
            "account_type": "asset",
            "normal_balance": "debit",
            "examples": ["Konstaterte tap", "Nedskrivninger"],
            "related_vat_codes": [],
        },
        {
            "account_id": "1900",
            "account_label": "Kasse",
            "account_class": "1",
            "account_class_label": "Eiendeler",
            "account_group": "19",
            "account_group_label": "Kontanter",
            "description": "Kontantbeholdning",
            "account_type": "asset",
            "normal_balance": "debit",
            "examples": ["Kassabeholdning", "Håndkasse"],
            "related_vat_codes": [],
        },
        {
            "account_id": "1905",
            "account_label": "Kasse, NOK",
            "account_class": "1",
            "account_class_label": "Eiendeler",
            "account_group": "19",
            "account_group_label": "Kontanter",
            "description": "Kontantbeholdning i norske kroner",
            "account_type": "asset",
            "normal_balance": "debit",
            "examples": ["Petty cash", "Håndkasse NOK"],
            "related_vat_codes": ["HIGH"],
        },
        {
            "account_id": "1920",
            "account_label": "Bankinnskudd (driftskonto)",
            "account_class": "1",
            "account_class_label": "Eiendeler",
            "account_group": "19",
            "account_group_label": "Bankinnskudd",
            "description": "Hovedkonto for daglig drift",
            "account_type": "asset",
            "normal_balance": "debit",
            "examples": ["Driftskonto", "Brukskonto hovedbank"],
            "related_vat_codes": ["HIGH"],
        },
        {
            "account_id": "1930",
            "account_label": "Skattetrekkskonto",
            "account_class": "1",
            "account_class_label": "Eiendeler",
            "account_group": "19",
            "account_group_label": "Skattetrekk",
            "description": "Konto for skattetrekk fra lønn",
            "account_type": "asset",
            "normal_balance": "debit",
            "examples": ["Skattetrekk arbeidsgiver", "Forskuddstrekk"],
            "related_vat_codes": [],
        },
        {
            "account_id": "2000",
            "account_label": "Aksjekapital",
            "account_class": "2",
            "account_class_label": "Egenkapital og gjeld",
            "account_group": "20",
            "account_group_label": "Innskutt egenkapital",
            "description": "Registrert aksjekapital",
            "account_type": "equity",
            "normal_balance": "credit",
            "examples": ["Ordinær aksjekapital", "Aksjekapital AS"],
            "related_vat_codes": [],
        },
        {
            "account_id": "2050",
            "account_label": "Annen egenkapital",
            "account_class": "2",
            "account_class_label": "Egenkapital og gjeld",
            "account_group": "20",
            "account_group_label": "Opptjent egenkapital",
            "description": "Annen innskutt egenkapital",
            "account_type": "equity",
            "normal_balance": "credit",
            "examples": ["Overkursfond", "Tilleggskapital"],
            "related_vat_codes": [],
        },
        {
            "account_id": "2400",
            "account_label": "Leverandørgjeld",
            "account_class": "2",
            "account_class_label": "Egenkapital og gjeld",
            "account_group": "24",
            "account_group_label": "Leverandørgjeld",
            "description": "Gjeld til leverandører",
            "account_type": "liability",
            "normal_balance": "credit",
            "examples": ["Faktura fra leverandører", "Varekjøp"],
            "related_vat_codes": ["HIGH", "MEDIUM", "LOW"],
        },
        {
            "account_id": "2600",
            "account_label": "Skyldig offentlige avgifter",
            "account_class": "2",
            "account_class_label": "Egenkapital og gjeld",
            "account_group": "26",
            "account_group_label": "Skyldige offentlige avgifter",
            "description": "Påløpt merverdiavgift og andre avgifter",
            "account_type": "liability",
            "normal_balance": "credit",
            "examples": ["MVA til betaling", "Arbeidsgiveravgift"],
            "related_vat_codes": [],
        },
        {
            "account_id": "2700",
            "account_label": "Utgående merverdiavgift",
            "account_class": "2",
            "account_class_label": "Egenkapital og gjeld",
            "account_group": "27",
            "account_group_label": "Utgående merverdiavgift",
            "description": "Utgående merverdiavgift på salg",
            "account_type": "liability",
            "normal_balance": "credit",
            "examples": ["MVA utgående 25 %", "MVA utgående 15 %"],
            "related_vat_codes": ["HIGH", "MEDIUM", "LOW"],
        },
        {
            "account_id": "2740",
            "account_label": "Oppgjørskonto merverdiavgift",
            "account_class": "2",
            "account_class_label": "Egenkapital og gjeld",
            "account_group": "27",
            "account_group_label": "Merverdiavgift oppgjør",
            "description": "Oppgjør av merverdiavgift til myndighetene",
            "account_type": "liability",
            "normal_balance": "credit",
            "examples": ["MVA oppgjør", "MVA til/fra Skatteetaten"],
            "related_vat_codes": [],
        },
        {
            "account_id": "3000",
            "account_label": "Salgsinntekt",
            "account_class": "3",
            "account_class_label": "Inntekter",
            "account_group": "30",
            "account_group_label": "Salgsinntekt varer og tjenester",
            "description": "Inntekter fra salg av varer og tjenester",
            "account_type": "income",
            "normal_balance": "credit",
            "examples": ["Produktsalg", "Tjenesteinntekter"],
            "related_vat_codes": ["HIGH"],
        },
        {
            "account_id": "3100",
            "account_label": "Salgsinntekt tjenester",
            "account_class": "3",
            "account_class_label": "Inntekter",
            "account_group": "31",
            "account_group_label": "Salgsinntekt tjenester",
            "description": "Inntekter fra tjenestesalg",
            "account_type": "income",
            "normal_balance": "credit",
            "examples": ["Konsulenttjenester", "Reparasjoner"],
            "related_vat_codes": ["HIGH"],
        },
        {
            "account_id": "4000",
            "account_label": "Varekjøp",
            "account_class": "4",
            "account_class_label": "Kostnader",
            "account_group": "40",
            "account_group_label": "Varekjøp",
            "description": "Kjøp av varer til videresalg",
            "account_type": "expense",
            "normal_balance": "debit",
            "examples": ["Innkjøp handelsvarer", "Råvarer"],
            "related_vat_codes": ["HIGH"],
        },
        {
            "account_id": "5000",
            "account_label": "Lønnskostnad",
            "account_class": "5",
            "account_class_label": "Kostnader",
            "account_group": "50",
            "account_group_label": "Lønninger",
            "description": "Lønn til ansatte",
            "account_type": "expense",
            "normal_balance": "debit",
            "examples": ["Fastlønn", "Timelønn"],
            "related_vat_codes": [],
        },
        {
            "account_id": "5400",
            "account_label": "Arbeidsgiveravgift",
            "account_class": "5",
            "account_class_label": "Kostnader",
            "account_group": "54",
            "account_group_label": "Arbeidsgiveravgift",
            "description": "Arbeidsgiveravgift til NAV",
            "account_type": "expense",
            "normal_balance": "debit",
            "examples": ["AGA 14.1 %", "AGA lønnskostnad"],
            "related_vat_codes": [],
        },
        {
            "account_id": "5401",
            "account_label": "Leie av maskiner",
            "account_class": "5",
            "account_class_label": "Kostnader",
            "account_group": "54",
            "account_group_label": "Leiekostnader",
            "description": "Leie av maskiner og utstyr",
            "account_type": "expense",
            "normal_balance": "debit",
            "examples": ["Maskinleie", "Utstyrsleie"],
            "related_vat_codes": ["HIGH"],
        },
        {
            "account_id": "5405",
            "account_label": "Husleie",
            "account_class": "5",
            "account_class_label": "Kostnader",
            "account_group": "54",
            "account_group_label": "Leiekostnader",
            "description": "Husleie for kontor og forretningslokaler",
            "account_type": "expense",
            "normal_balance": "debit",
            "examples": ["Kontorleie", "Forretningsleie"],
            "related_vat_codes": ["HIGH"],
        },
        {
            "account_id": "5410",
            "account_label": "Renhold og vakthold",
            "account_class": "5",
            "account_class_label": "Kostnader",
            "account_group": "54",
            "account_group_label": "Leiekostnader",
            "description": "Kostnader til renhold og vakthold",
            "account_type": "expense",
            "normal_balance": "debit",
            "examples": ["Rengjøring", "Vakthold", "Sikkerhetstjenester"],
            "related_vat_codes": ["HIGH"],
        },
        {
            "account_id": "5900",
            "account_label": "Lønn til ansatte",
            "account_class": "5",
            "account_class_label": "Kostnader",
            "account_group": "59",
            "account_group_label": "Personalkostnader",
            "description": "Lønnskostnader til ansatte",
            "account_type": "expense",
            "normal_balance": "debit",
            "examples": ["Månedlig lønn", "Timelønn", "Overtid"],
            "related_vat_codes": [],
        },
        {
            "account_id": "6000",
            "account_label": "Leiekostnader",
            "account_class": "6",
            "account_class_label": "Kostnader",
            "account_group": "60",
            "account_group_label": "Husleie og lokalkostnader",
            "description": "Leie av lokaler",
            "account_type": "expense",
            "normal_balance": "debit",
            "examples": ["Kontorleie", "Lagerlokaler"],
            "related_vat_codes": ["HIGH"],
        },
        {
            "account_id": "6010",
            "account_label": "Forbruksmateriell",
            "account_class": "6",
            "account_class_label": "Kostnader",
            "account_group": "60",
            "account_group_label": "Forbruksvarer",
            "description": "Forbruksmateriell og rekvisita",
            "account_type": "expense",
            "normal_balance": "debit",
            "examples": ["Kontorrekvisita", "Forbruksvarer", "Småmateriell"],
            "related_vat_codes": ["HIGH"],
        },
        {
            "account_id": "6100",
            "account_label": "Strøm, oppvarming og renovasjon",
            "account_class": "6",
            "account_class_label": "Kostnader",
            "account_group": "61",
            "account_group_label": "Strøm og oppvarming",
            "description": "Kostnader til strøm, oppvarming og renovasjon",
            "account_type": "expense",
            "normal_balance": "debit",
            "examples": ["Strømkostnader", "Vann og avløp"],
            "related_vat_codes": ["MEDIUM"],
        },
        {
            "account_id": "6300",
            "account_label": "Reparasjon og vedlikehold",
            "account_class": "6",
            "account_class_label": "Kostnader",
            "account_group": "63",
            "account_group_label": "Reparasjon og vedlikehold",
            "description": "Kostnader til reparasjon og vedlikehold",
            "account_type": "expense",
            "normal_balance": "debit",
            "examples": ["Vedlikehold bygg", "Reparasjon maskiner"],
            "related_vat_codes": ["HIGH"],
        },
        {
            "account_id": "6340",
            "account_label": "Fremmede tjenester",
            "account_class": "6",
            "account_class_label": "Kostnader",
            "account_group": "63",
            "account_group_label": "Fremmede tjenester",
            "description": "Kjøp av fremmede tjenester",
            "account_type": "expense",
            "normal_balance": "debit",
            "examples": ["Konsulenter", "Regnskapstjenester"],
            "related_vat_codes": ["HIGH", "EXEMPT", "REVERSE_CHARGE"],
        },
        {
            "account_id": "6800",
            "account_label": "Kontorkostnader",
            "account_class": "6",
            "account_class_label": "Kostnader",
            "account_group": "68",
            "account_group_label": "Kontorkostnader",
            "description": "Kontorrekvisita og kontorkostnader",
            "account_type": "expense",
            "normal_balance": "debit",
            "examples": ["Kontormateriell", "Porto"],
            "related_vat_codes": ["HIGH"],
        },
        {
            "account_id": "6550",
            "account_label": "Telefon og internett",
            "account_class": "6",
            "account_class_label": "Kostnader",
            "account_group": "65",
            "account_group_label": "IT og telekommunikasjon",
            "description": "Kostnader til telefon og datakommunikasjon",
            "account_type": "expense",
            "normal_balance": "debit",
            "examples": ["Mobilabonnement", "Bredbånd", "Fiber"],
            "related_vat_codes": ["HIGH"],
        },
        {
            "account_id": "6551",
            "account_label": "Programvarelisenser",
            "account_class": "6",
            "account_class_label": "Kostnader",
            "account_group": "65",
            "account_group_label": "IT og telekommunikasjon",
            "description": "Lisenser og abonnementer for programvare",
            "account_type": "expense",
            "normal_balance": "debit",
            "examples": ["SaaS-abonnementer", "Microsoft 365", "Adobe Creative Cloud"],
            "related_vat_codes": ["HIGH"],
        },
        {
            "account_id": "6900",
            "account_label": "Telefon og internett",
            "account_class": "6",
            "account_class_label": "Kostnader",
            "account_group": "69",
            "account_group_label": "Telefon og internett",
            "description": "Kostnader til telefon og datakommunikasjon",
            "account_type": "expense",
            "normal_balance": "debit",
            "examples": ["Mobilabonnement", "Bredbånd"],
            "related_vat_codes": ["HIGH"],
        },
        {
            "account_id": "7000",
            "account_label": "Reisekostnad",
            "account_class": "7",
            "account_class_label": "Kostnader",
            "account_group": "70",
            "account_group_label": "Reisekostnader",
            "description": "Reisekostnader for ansatte",
            "account_type": "expense",
            "normal_balance": "debit",
            "examples": ["Togbilletter", "Flybilletter"],
            "related_vat_codes": ["HIGH", "LOW"],
        },
        {
            "account_id": "7140",
            "account_label": "Kostnad opphold, hotell",
            "account_class": "7",
            "account_class_label": "Kostnader",
            "account_group": "71",
            "account_group_label": "Opphold",
            "description": "Overnatting på hotell",
            "account_type": "expense",
            "normal_balance": "debit",
            "examples": ["Hotellovernatting", "Konferansehotell"],
            "related_vat_codes": ["LOW"],
        },
        {
            "account_id": "7160",
            "account_label": "Kostnad opphold, mat",
            "account_class": "7",
            "account_class_label": "Kostnader",
            "account_group": "71",
            "account_group_label": "Opphold",
            "description": "Kostnader til mat under reise",
            "account_type": "expense",
            "normal_balance": "debit",
            "examples": ["Restaurantbesøk", "Kantinekjøp"],
            "related_vat_codes": ["MEDIUM"],
        },
        {
            "account_id": "7320",
            "account_label": "Drivstoff",
            "account_class": "7",
            "account_class_label": "Kostnader",
            "account_group": "73",
            "account_group_label": "Bilkostnader",
            "description": "Drivstoff til firmabil",
            "account_type": "expense",
            "normal_balance": "debit",
            "examples": ["Bensin", "Diesel"],
            "related_vat_codes": ["HIGH"],
        },
        {
            "account_id": "8050",
            "account_label": "Renteinntekt",
            "account_class": "8",
            "account_class_label": "Finansposter",
            "account_group": "80",
            "account_group_label": "Renteinntekter",
            "description": "Renteinntekter fra bankinnskudd",
            "account_type": "income",
            "normal_balance": "credit",
            "examples": ["Bankrente", "Sparerenteinntekt"],
            "related_vat_codes": [],
        },
        {
            "account_id": "8150",
            "account_label": "Rentekostnad",
            "account_class": "8",
            "account_class_label": "Finansposter",
            "account_group": "81",
            "account_group_label": "Rentekostnader",
            "description": "Rentekostnader på lån",
            "account_type": "expense",
            "normal_balance": "debit",
            "examples": ["Banklånsrenter", "Kredittgjeld"],
            "related_vat_codes": [],
        },
        {
            "account_id": "8300",
            "account_label": "Renteinntekter",
            "account_class": "8",
            "account_class_label": "Finansposter",
            "account_group": "83",
            "account_group_label": "Renteinntekter",
            "description": "Renteinntekter fra bank og andre finansielle investeringer",
            "account_type": "income",
            "normal_balance": "credit",
            "examples": ["Bankrente", "Sparerente", "Obligasjonsrente"],
            "related_vat_codes": [],
        },
    ]

    for acc_data in accounts_data:
        acc_data["is_standard"] = True
        acc_data["is_active"] = True
        acc_data["source_standard"] = "NS 4102"
        acc_data["jurisdiction"] = "NO"
        acc_data["last_updated"] = timestamp

    validated_accounts: list[ChartOfAccountsEntry] = []
    for account_dict in accounts_data:
        try:
            validated_account = ChartOfAccountsEntry(**account_dict)
            validated_accounts.append(validated_account)
        except Exception as e:
            account_id = account_dict.get("account_id", "unknown")
            logger.error(f"Validation failed for account {account_id}: {e}")
            raise

    return validated_accounts


def seed_chart_of_accounts(silver_dir: Path | None = None) -> int:
    """Generate NS 4102 chart of accounts to silver layer."""
    logger.info("Seeding Chart of Accounts (NS 4102)")

    if silver_dir is None:
        silver_dir = get_silver_dir()

    silver_dir.mkdir(parents=True, exist_ok=True)
    output_path = silver_dir / "chart_of_accounts.json"

    # Get validated typed accounts
    accounts = get_ns4102_accounts()

    # Convert to dicts for JSON serialization
    validated_accounts = [account.model_dump() for account in accounts]

    # Write to JSON
    with output_path.open("w", encoding="utf-8") as f:
        json.dump(validated_accounts, f, ensure_ascii=False, indent=2)

    logger.info(
        f"✓ Chart of Accounts: {len(validated_accounts)} accounts → {output_path.name}"
    )

    # Print summary by class
    class_counts: dict[str, int] = {}
    for acc in validated_accounts:
        class_label = acc["account_class_label"]
        class_counts[class_label] = class_counts.get(class_label, 0) + 1

    for class_label, count in sorted(class_counts.items()):
        logger.info(f"  {class_label}: {count} accounts")

    return 0
