name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: uv sync

    - name: Run ruff check
      run: uv run ruff check .

    - name: Run ruff format check
      run: uv run ruff format --check .

    - name: Run mypy type checking
      run: uv run mypy modules scripts

    - name: Run unit tests
      run: uv run python -m pytest tests/ -v

    - name: Test script imports
      run: |
        uv run python -c "import modules.logger; print('Logger module OK')"
        uv run python -c "import modules.schemas; print('Schemas module OK')"
        uv run python -c "import modules.parsers; print('Parsers module OK')"
        uv run python -c "import modules.validation; print('Validation module OK')"

    - name: Test script execution
      run: |
        uv run konto-ingest --help
        uv run process-rates-to-silver --help
        uv run validate-silver --help

  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: uv sync

    - name: Run comprehensive linting
      run: |
        echo "Running ruff check..."
        uv run ruff check . --output-format=github
        echo "Running ruff format check..."
        uv run ruff format --check . --diff
        echo "Running mypy type checking..."
        uv run mypy modules scripts --show-error-codes

  build-test:
    runs-on: ubuntu-latest
    needs: [test, lint-and-format]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: uv sync

    - name: Test package build
      run: |
        echo "Testing package build..."
        uv build --wheel
        echo "Package build successful"

    - name: Test installation
      run: |
        echo "Testing package installation..."
        uv run python -c "import konto_ingestion; print('Package imports successfully')" || echo "Package not yet installable"
