name: Code Formatting

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  format:
    runs-on: ubuntu-latest
    name: Format Code
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: uv sync

    - name: Run ruff format
      run: |
        echo "Running ruff format..."
        uv run ruff format .

    - name: Run ruff check with auto-fix
      run: |
        echo "Running ruff check with auto-fix..."
        uv run ruff check . --fix

    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "Files were formatted"
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "No files needed formatting"
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "style: auto-format code with ruff"
        git push
